### ISSUE TITLE
Check requisites fails

### ISSUE THREAD

**Issue by RaulBernal** [hellresistor/BCNA-Cosmos-Testnet#3]
[INFO]  Checking System Compatibility... 
[OK]  >= 2 Cores 
[OK]  >= 4GB RAM 
[ERRO]  < 80 GB, Upgrade more 
[ERRO]  Failing Check System 

S.ficheros     Tamaño Usados  Disp Uso% Montado en
udev             3,9G      0  3,9G   0% /dev
tmpfs            789M   2,3M  787M   1% /run
/dev/sdb1        212G    78G  125G  39% /

**Comment by hellresistor** [comment]
culpa de lo /dev/sdb :) 

Change line 43 ;) from sda1 to sdb1
