### ISSUE TITLE
Config must be edited before exec script

### ISSUE THREAD

**Issue by RaulBernal** [hellresistor/BCNA-Cosmos-Testnet#4]
git clone https://github.com/hellresistor/BCNA-Cosmos-Testnet.git
chmod -R +x BCNA-Cosmos-Testnet && cd "$PWD"/BCNA-Cosmos-Testnet
**_nano CONFIG_**
bash BCNA-Cosmos-Install.sh

**Comment by hellresistor** [comment]
done
